### PR TITLE
Closes #2072 - Don't emit screen changes unless distinct.

### LINKED ISSUE #2072: Youtube loses control after menu bar
## Steps to reproduce
- Open youtube, play video
- Play with controls, make it visible
- Press menu to go to overlay
- Press menu again to return to video
- Access youtube video control, or exit the video

### Expected behavior
- Control is visible, and video can be stopped with back button

### Actual behavior
- App does not respond to inputs, other than menu overlay

### Device information
* Fire TV device: Gen 2 stick

### PR DESCRIPTION
**Pull request by liuche**
Didn't add a changelog because this fixes a new regression created in 3.7, didn't add a test but I added another item to #1420 .

### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 1]
```diff
@@ -154,7 +154,7 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
     }
 
     override fun onEngineViewCreated(engineView: EngineView): Disposable? {
-        return serviceLocator?.screenController?.currentActiveScreen?.subscribe {
+        return serviceLocator?.screenController?.currentActiveScreen?.distinctUntilChanged()?.subscribe {
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: This is probably going to be a gotcha in other parts of the codebase, too.  I think we can reasonably assume that this observable should always use `distinctUntilChanged`, could you add this operator in `ScreenController` line 37 instead?

Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: By convention, individual Rx operators are generally put on separate lines.  So this would be 

```kotlin
serviceLocator?.screenController?.currentActiveScreen
    ?.distinctUntilChanged()
    ?.subscribe {
```
or
```kotlin
serviceLocator?.screenController?.currentActiveScreen?.distinctUntilChanged()
    ?.subscribe {
```

Comment (liuche) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: Yes! Makes sense.

I didn't look into why this was emitting multiple times, which was also strange.
