### PR TITLE
#2133: Hint bar visibility fix

### LINKED ISSUE #2133: Empty hint bar appears on bottom of screen
## Steps to reproduce
- Open debug build
- Loda a page

### Expected behavior
No hint bar or hint bar with content

### Actual behavior
Hint bar appears but is empty

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: master
* Earliest affected Firefox version: ?

~I think this is  a regression from https://github.com/mozilla-mobile/firefox-tv/issues/2029 (which just landed).~
EDIT: regression from #2118

### PR DESCRIPTION
**Pull request by psymoon**
Closes #2133 
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt [hunk 1]
```diff
@@ -37,12 +38,29 @@ object HintBinder {
...
                     }
                     .subscribe { shouldDisplay ->
-                        hintContainer.isVisible = true
                         val translationY = when (shouldDisplay) {
                             true -> 0f
                             false -> hintContainer.height.toFloat()
                         }
+
                         hintContainer.animate()
+                                // If the hint bar is appearing, set the hintContainer.isVisible
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt]: nit: this comment is redundant to the code and likely to get outdated: I'd remove it.

File: app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt [hunk 2]
```diff
@@ -37,12 +38,29 @@ object HintBinder {
...
+                                // to true before the animation begins. If the hint bar is
+                                // disappearing, set the hintContainer.isiVisible to false after
+                                // the animation ends.
+                                .setListener(object : Animator.AnimatorListener {
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt]: nit: you can use `AnimatorListenerAdapter` so you don't have to override `onAnimationCancel/Repeat` (note: you don't need to call super either in the other methods).

File: app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt [hunk 3]
```diff
@@ -37,12 +38,29 @@ object HintBinder {
                                 .start()
                     }
                     .subscribe { shouldDisplay ->
-                        hintContainer.isVisible = true
                         val translationY = when (shouldDisplay) {
                             true -> 0f
                             false -> hintContainer.height.toFloat()
                         }
+
                         hintContainer.animate()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/hint/HintBinder.kt]: nit: can we add a comment somewhere in this method (maybe here or at the top) warning devs to be _very_ careful when changing this code to ensure the experiment stays disabled when A/B testing is disabled? I'm concerned the code isn't explicit enough about this (e.g. like early returning from this binding method if `ExperimentsrProvider.shouldShowHintBar` returns false).
