### PR TITLE
Closes #770: [Home] Update overlay buttons to reflect current navigat…

### LINKED ISSUE #770: [Home] Update overlay buttons to reflect current navigation state
Reflect the "home" state without a browser stack in the overlay buttons.

Back, forward, refresh, pin should all be disabled and un-activated.

This should also fix the problems with the navigation buttons incorrectly gaining focus when moving through tiles (introduced in #768).

### PR DESCRIPTION
**Pull request by bkmunar**
…ion state

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 1]
```diff
@@ -179,7 +181,14 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
         navButtonForward.isFocusable = canGoForward
         navButtonForward.alpha = if (canGoForward) NAVIGATION_BUTTON_ENABLED_ALPHA else NAVIGATION_BUTTON_DISABLED_ALPHA
 
+        val isPinEnabled = navigationStateProvider?.isPinEnabled() ?: false
+        pinButton.isEnabled = isPinEnabled
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: nit: since we repeat this code so much, can we add a helper function?

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 2]
```diff
@@ -179,7 +181,14 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
...
         pinButton.isChecked = navigationStateProvider?.isURLPinned() ?: false
+        pinButton.alpha = if (isPinEnabled) NAVIGATION_BUTTON_ENABLED_ALPHA else NAVIGATION_BUTTON_DISABLED_ALPHA
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: nit: Do we need `isFocusable` too, like the other buttons? Another reason we want helper functions. :)
