### PR TITLE
Fixes #1408: megatile focus on fresh install

### LINKED ISSUE #1408: On a fresh install, Pocket megatile is skipped when scrolling down
## Steps to reproduce
Uninstall Firefox, this only happens on a fresh install
Install Firefox, and click through onboarding screens
Scroll down from nav bar

### Expected behavior
Pocket megatile gets highlighted

### Actual behavior
Nav highlight skips down to home tiles. Scrolling back up works again.

### Device information

* Fire TV device: Cube
* Firefox version: master 1213142

### PR DESCRIPTION
**Pull request by Baron-Severin**
Root cause:
Previously, whether or not to set focus on the megatile was determined by checking view visibility. When onboarding is up, views that we would normally expect to be visible are not. The solution to this is to check based on VM state, rather than view state

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt [hunk 1]
```diff
@@ -55,6 +56,11 @@ open class FirefoxApplication : LocaleAwareApplication() {
         }
     }
 
+    private fun initServiceLocator() {
+        val getLanguage = { LocaleManager.getInstance().getCurrentLanguage(this) }
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt]: Can this be declared inside `ServiceLocator` (which already has access to `applicationContext`) or even `ViewModelFactory`? It's an unnecessary dependency for the factory class when it's only used for `PocketViewModel`

File: app/src/main/java/org/mozilla/tv/firefox/ViewModelFactory.kt [hunk 2]
```diff
@@ -20,17 +20,24 @@ import org.mozilla.tv.firefox.utils.ServiceLocator
  * val myViewModel = ViewModelProviders.of(this, factory).get(ExampleViewModel::class.java)
  * ```
  */
-class ViewModelFactory(private val serviceLocator: ServiceLocator) : ViewModelProvider.Factory {
+class ViewModelFactory(private val serviceLocator: ServiceLocator, private val getCurrentLanguage: () -> String) :
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/ViewModelFactory.kt]: See above

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt [hunk 3]
```diff
@@ -266,12 +253,17 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
...
+                    showMegaTileError()
+                }
                 is PocketViewModel.State.Feed -> {
+                    pocketVideoMegaTileView.visibility = View.VISIBLE
                     pocketVideoMegaTileView.setContent(state.feed)
                 }
+                is PocketViewModel.State.NotDisplayed -> pocketVideoMegaTileView.visibility = View.GONE
                 null -> return@Observer
-            }
+            }.forceExhaustive
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt]: Is `forceExhaustive` necessary if there is an else statement?

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt [hunk 4]
```diff
@@ -372,8 +364,8 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
         }
 
         navUrlInput.nextFocusDownId = when {
-            pocketVideosContainer.isEffectivelyVisible -> R.id.pocketVideoMegaTileView
-            megaTileTryAgainButton.isEffectivelyVisible -> R.id.megaTileTryAgainButton
+            pocketViewModel.state.value is PocketViewModel.State.Feed -> R.id.pocketVideoMegaTileView
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt]: nit: why is one reference equality expression use `is` while the other use `===`?

File: app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt [hunk 5]
```diff
@@ -50,10 +50,11 @@ class PocketVideoFragment : Fragment() {
         val viewModel = ViewModelProviders.of(this, factory).get(PocketViewModel::class.java)
 
         viewModel.state.observe(viewLifecycleOwner, Observer<PocketViewModel.State> { state ->
-            state ?: return@Observer
             when (state) {
                 is PocketViewModel.State.Error -> { /* TODO: #769: display error screen */ }
                 is PocketViewModel.State.Feed -> adapter.setVideos(state.feed)
+                is PocketViewModel.State.NotDisplayed -> { }
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt]: What does this do?

File: app/src/main/java/org/mozilla/tv/firefox/utils/ServiceLocator.kt [hunk 6]
```diff
@@ -44,13 +44,13 @@ import org.mozilla.tv.firefox.pocket.PocketVideoRepo
  *   open val telemetry: TelemetryInterface by lazy { SentryWrapper() }
  *   ```
  */
-open class ServiceLocator(val app: Application) {
+open class ServiceLocator(val app: Application, getCurrentLanguage: () -> String) {
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/utils/ServiceLocator.kt]: See above about having redundant dependencies. There could be a better resolution while satisfying mockability in testing

File: app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleManager.java [hunk 7]
```diff
@@ -283,14 +283,14 @@ public Locale getCurrentLocale(@NonNull Context context) {
         return currentLocale = Locales.parseLocaleCode(current);
     }
 
-    public boolean currentLanguageIsEnglish(@NonNull Context context) {
+    @NonNull
+    public String getCurrentLanguage(@NonNull Context context) {
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleManager.java]: Why was this changed? It looks like it's only used in `PocketViewModel` to check for English anyway

File: app/src/main/java/org/mozilla/tv/firefox/pocket/PocketViewModel.kt [hunk 8]
```diff
@@ -42,14 +47,21 @@ class PocketViewModel(private val pocketVideoRepo: PocketVideoRepo, pocketRepoCa
...
+    val state = pocketRepoCache.feedState
+        .map { repoState ->
+            when (repoState) {
+                is PocketVideoRepo.FeedState.Loading -> State.Feed(loadingPlaceholders)
+                is PocketVideoRepo.FeedState.LoadComplete -> State.Feed(repoState.videos)
+                is PocketVideoRepo.FeedState.NoAPIKey -> State.Feed(noKeyPlaceholders)
+                is PocketVideoRepo.FeedState.FetchFailed -> State.Error
+            }
+        }.map {
+            if (getCurrentLanguage().toLowerCase().startsWith("en")) it
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/pocket/PocketViewModel.kt]: See above for `getCurrentLanguage()`

File: app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt]: Good point.  I'll pass application into the factory and grab this in there.

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt (hunk 3 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt]: IMO, `forceExhaustive` should be on every when expression that doesn't return a value (it was a mistake on my part not to have it here in the first place).  Having an else statement will cause an otherwise non-exhaustive when expression to compile, even with `forceExhaustive` on, but for that reason I prefer to avoid else branches when possible.  The advantage here is that, if we ever add a new type to PocketViewModel.State this will force us to update the code everywhere it's used.

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt (hunk 4 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/BrowserNavigationOverlay.kt]: Yeah, that's annoying and I'm not a big fan of it.  `Feed` is a data class (it carries video information) whereas `Error` is an object, so testing its type and testing referential equality are the same.  Testing `Error` with an `is` results in a linting error.  I'm not sure what the best way to approach this is, tbh.

File: app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt (hunk 5 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt]: If our state is `notDisplayed` then we shouldn't even be able to reach this fragment.  I can add a comment in explaining that.  Do you think we should throw an exception there as well?

File: app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleManager.java (hunk 7 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleManager.java]: Tbh, I don't remember.  Maybe I thought it would be useful in other contexts as well?  I can change it back.

File: app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt [hunk 9]
```diff
@@ -55,6 +55,10 @@ open class FirefoxApplication : LocaleAwareApplication() {
         }
     }
 
+    private fun initServiceLocator() {
```
Comment (psymoon) [inline app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt]: nit: Do you think this method is necessary?

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/FirefoxApplication.kt]: Not anymore.  I'll pull it out.
