### PR TITLE
Fix Pocket and Settings focus after page load

### LINKED ISSUE #1888: Regression: Fragment changes do not handle focus correctly
## Steps to reproduce
Open Pocket or Settings fragment

### Expected behavior
Item is focused

### Actual behavior
Nothing is focused

### Device information
* Fire TV device: Stick
* Latest affected Firefox version: master e5a56a9f4e67e253d6e3786d25d9291dd3958f41
* Earliest affected Firefox version: 3.4.1 master

I think this is a regression from #1664 due to changing focus between webrender/overlay fragment, but not handling other fragments.

### PR DESCRIPTION
**Pull request by liuche**
Closes #1888 
Fixed the fragment focus test problem - apparently `click()` doesn't maintain focus, so a keypress solution was necessary.

~~Also, this doesn't maintain "previous button focus on return to overlay".~~ Actually, we removed cached focus when returning to overlay in the re-architecture.

### Pull Request checklist

- [X] This PR includes thorough **tests** or an explanation of why it does not
- [X] This PR includes a **CHANGELOG entry** or does not need one
- [X] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [X] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/architecture/FocusOnShowFragment.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+package org.mozilla.tv.firefox.architecture
+
+import androidx.fragment.app.Fragment
+
+open class FocusOnShowFragment : Fragment() {
+    override fun onHiddenChanged(hidden: Boolean) {
+        if (!hidden) {
+            view?.requestFocus()
+        }
+        super.onHiddenChanged(hidden)
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/architecture/FocusOnShowFragment.kt]: I'm not super happy with how inflexible it is to have all of our fragments extend this class.  I wonder if we could find a better way to accomplish this via composition instead.  The best I've come up with so far is this, but there's probably a much nicer alternative that I haven't thought of.

```kotlin
class FocusOnShowDelegate {
    fun onHiddenChanged(fragment: Fragment, hidden: Boolean) {
        if (!hidden) {
            fragment.view?.requestFocus()
        }
    }
}

class SettingsFragment : Fragment() {
...
    override fun onHiddenChanged(hidden: Boolean) {
        FocusOnShowDelegate().onHiddenChanged(this, hidden)
        super.onHiddenChanged(hidden)
    }
...
}
```

File: app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt [hunk 2]
```diff
@@ -193,12 +192,13 @@ class MainActivity : LocaleAwareAppCompatActivity(), OnUrlEnteredListener, Media
...
         TelemetryIntegration.INSTANCE.saveRemoteControlInformation(applicationContext, event)
 
+        return videoVoiceCommandMediaSession.dispatchKeyEvent(event) ||
+                serviceLocator.screenController.dispatchKeyEvent(event, fragmentManager) ||
+                super.dispatchKeyEvent(event)
+
+        /*
         if (event.keyCode == KeyEvent.KEYCODE_MENU) {
             if (event.action == KeyEvent.ACTION_DOWN) {
                 serviceLocator.screenController.handleMenu(supportFragmentManager)
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt]: Nit: is there any reason we need this commented code, or was this an oversight?

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 3]
```diff
@@ -150,6 +151,17 @@ class ScreenController {
...
     }
 
+    fun dispatchKeyEvent(keyEvent: KeyEvent, fragmentManager: FragmentManager): Boolean {
+        if (keyEvent.keyCode == KeyEvent.KEYCODE_MENU && keyEvent.action == KeyEvent.ACTION_DOWN) {
+            return handleMenu(fragmentManager)
+        }
+
+        if (currentActiveScreen.value == ScreenControllerStateMachine.ActiveScreen.WEB_RENDER) {
+            if (fragmentManager.webRenderFragment().dispatchKeyEvent(keyEvent)) return true
+        }
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Optional nit: these conditional statements are very simple, but also pretty long, which I find makes them a little hard to read.  I find code like the below to be helpful in this kind of situation.

```kotlin
    fun dispatchKeyEvent(keyEvent: KeyEvent, fragmentManager: FragmentManager): Boolean {
        val menuDown = keyEvent.keyCode == KeyEvent.KEYCODE_MENU && keyEvent.action == KeyEvent.ACTION_DOWN
        if (menuDown) {
            return handleMenu(fragmentManager)
        }

        val webRenderIsActive = currentActiveScreen.value == ScreenControllerStateMachine.ActiveScreen.WEB_RENDER
        if (webRenderIsActive) {
            if (fragmentManager.webRenderFragment().dispatchKeyEvent(keyEvent)) return true
        }
        return false
    }
```

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 4]
```diff
@@ -150,6 +151,17 @@ class ScreenController {
         transaction.commit()
     }
 
+    fun dispatchKeyEvent(keyEvent: KeyEvent, fragmentManager: FragmentManager): Boolean {
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: I'm not super excited that we're adding another stop for key events (they already bounce around a lot), but this does seem like a logical way to organize it.  No action needed on this, just general grumbling.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt [hunk 5]
```diff
@@ -134,4 +135,14 @@ class BasicNavigationTest {
             assertActivityFinishing(activityTestRule)
         }
     }
+    @Test
+    fun screenNavigationFocusTest() {
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt]: I wonder if focus testing might deserve its own class entirely.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 6]
```diff
@@ -123,6 +122,31 @@ class NavigationOverlayRobot {
             return SettingsRobot.Transition()
         }
 
+        /*
+         * Navigate to the settings button using keypresses and open, and maintain focus.
+         * Using click() to select buttons removes focus, so this is an alternative way to open
+         * Settings.
+         */
+        fun navigateToSettingsAndOpen(interact: SettingsRobot.() -> Unit): SettingsRobot.Transition {
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: Nit: `linearNavigateToSettingsAndOpen`

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 7]
```diff
@@ -123,6 +122,31 @@ class NavigationOverlayRobot {
...
+            // We hard-code this navigiation pattern because making a generic way to linearly navigate
+            // is very difficult within Espresso. Espresso does not allow branching, and relies on
+            // assertions, so a generic keypress navigation with conditional checks is not worth writing
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: I find `Espresso does not allow branching, and relies on assertions` to be a little bit unclear.  Maybe `Espresso supports asserting view state, but not querying it.  Because of this, we can't write conditional logic based on the currently focused view.`

It's pretty verbose, but I think it communicates the problem better.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 8]
```diff
@@ -123,6 +122,31 @@ class NavigationOverlayRobot {
...
+            // for a single test. Can revisit if more focus-related tests are written.
+            device.apply {
+                // This will need to change if the button layout changes.
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: Optional nit: += `However, such layout changes are infrequent, and updating this will be easy`

File: app/src/main/java/org/mozilla/tv/firefox/architecture/FocusOnShowFragment.kt (hunk 1 above)
Comment (liuche) [reply app/src/main/java/org/mozilla/tv/firefox/architecture/FocusOnShowFragment.kt]: Yeah, that's at least a little better - I'll do that.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt (hunk 5 above)
Comment (liuche) [reply app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt]: I took Navigation to mean "navigation within the app" so in this case, I put it here to handle navigation to other fragments.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 9]
```diff
@@ -123,6 +122,32 @@ class NavigationOverlayRobot {
...
+        fun linearNavigateToSettingsAndOpen(interact: SettingsRobot.() -> Unit): SettingsRobot.Transition {
+            // We hard-code this navigiation pattern because making a generic way to linearly navigate
+            // is very difficult within Espresso. Espresso supports asserting view state, but not
+            // querying it. Because of this, we can't write conditional logic based on the currently
+            // focused view.
+            device.apply {
+                // This will need to change if the button layout changes. However, such layout
+                // changes are infrequent, and updating this will be easy.
+                pressDPadUp()
+                pressDPadRight()
```
Comment (mcomella) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: nit: `repeat(5) { pressDPadRight() }`

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt [hunk 10]
```diff
@@ -134,4 +135,14 @@ class BasicNavigationTest {
...
+        // Navigate to settings via keypresses, to maintain focus.
+        navigationOverlay {
+        }.enterUrlAndEnterToBrowser(Uri.parse("firefox:about")) {
+        }.openOverlay {
+        }.linearNavigateToSettingsAndOpen {
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt]: Nit: I think `// Navigate to settings via keypresses, to maintain focus.` might make more sense just above line 144.

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt (hunk 4 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Better here than in `WebRenderFragment`, too.

File: app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleAwareFragment.java [hunk 11]
```diff
@@ -2,13 +2,12 @@
...
-
 package org.mozilla.tv.firefox.components.locale;
 
-import androidx.fragment.app.Fragment;
-
 import java.util.Locale;
 
+import androidx.fragment.app.Fragment;
+
 public abstract class LocaleAwareFragment extends Fragment {
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleAwareFragment.java]: Nit: not sure why there's spacing between these imports.  Any chance you could run `optimize import statements` on this file before merging?

File: app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt [hunk 12]
```diff
@@ -83,23 +82,16 @@ class PocketVideoFragment : Fragment() {
         compositeDisposable.clear()
     }
 
-    // When menu is pressed from the Pocket feed, go back to overlay
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt]: Did you verify that the behavior in this comment is still present after this change?

Comment (liuche) [reply app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoFragment.kt]: Yep! This code was actually listed as unused by the compiler so I just removed it.

File: app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleAwareFragment.java (hunk 11 above)
Comment (liuche) [reply app/src/main/java/org/mozilla/tv/firefox/components/locale/LocaleAwareFragment.java]: Weird, optimize imports didn't do anything, but I removed that extra line anyway.
