### PR TITLE
Fixes #2937: fix pre-boarding dismiss telemetry

### LINKED ISSUE #2937: [FxA] "Not now" button telemetry is incorrect: sent every time preboarding is shown
https://searchfox.org/mozilla-mobile/rev/5a11d65b0db47eab3a32946148ff68bd0d452ff5/firefox-tv/app/src/main/java/org/mozilla/tv/firefox/onboarding/ReceiveTabPreboardingActivity.kt#55 - we're currently triggering the "Not now" telemetry every time the receive tabs preboarding is shown, rather than when "Not now" is pressed.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5+ master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### PR DESCRIPTION
**Pull request by Baron-Severin**
## Checklist

- [X] Confirm the **acceptance criteria** is fully satisfied in the issue(s) this PR will close
- [ ] Add thorough **tests** or an explanation of why it does not
- [X] Add a **CHANGELOG entry** if applicable
Not user facing
- [X] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-notneeded`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/onboarding/ReceiveTabPreboardingActivity.kt [hunk 1]
```diff
@@ -42,6 +42,7 @@ class ReceiveTabPreboardingActivity : AppCompatActivity() {
 
         buttonNotNow.setOnClickListener {
             finish()
+            TelemetryIntegration.INSTANCE.fxaPreboardingDismissButtonClickEvent()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/onboarding/ReceiveTabPreboardingActivity.kt]: I spoke with athomasmoz & the data folks: **we want to rename the probe**. The recommendation was that the data owner should decide but the recommendation (for this specific case) from the data team is to rename it because it will make analysis easier.

Can you rename the probe and update the docs, including mentioning the old probe is deprecated and linking to the issue with the bug?

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/onboarding/ReceiveTabPreboardingActivity.kt]: Good call!  Will do.

File: docs/telemetry.md [hunk 2]
```diff
@@ -123,6 +123,9 @@ does not count if the overlay is opened by the user pressing "back" through thei
 (††) This probe was broken in an unknown release; it was fixed in v3.9. This probe does not count if the users exit the
 overlay (without taking an action) _and the app_ by pressing the back button when the overlay is opened.
 
+(†††) There was a bug in the implementation of `fxa_preboarding_not_now` that caused it to be sent too frequently. When
```
Comment (mcomella) [inline docs/telemetry.md]: nit: include a link to the bug.
