### PR TITLE
Fixes #1155: fixes white screen on nav to firefox:home

### LINKED ISSUE #1155: Going to firefox:home shows white screen, makes app unusuable
## Steps to reproduce
Open Firefox app
go to URL bar, and either type firefox:home or press Enter if the bar is prepopulated with 'firefox:home' text

### Expected behavior
Shows main tiles page

### Actual behavior
White screen, app becomes unusuable. need to force stop

### Device information

* Fire TV device: Basic TV stick
* Firefox version: master branch

### PR DESCRIPTION
**Pull request by Baron-Severin**
I think that making this check in the BrowserFragment is wrong, but setting the visibility here is probably also wrong.  Without refactoring how we handle NavigationEvents, I don't see a better way to do this.

### CODE REVIEW

**Comment by Baron-Severin** [comment]
FWIW, I spent around an hour trying to add tests, but was unable to get BrowerFragment into a testing harness.

File: app/src/main/java/org/mozilla/focus/browser/BrowserFragment.kt [hunk 1]
```diff
@@ -128,7 +128,7 @@ class BrowserFragment : EngineViewLifecycleFragment(), Session.Observer {
             NavigationEvent.SETTINGS -> ScreenController.showSettingsScreen(fragmentManager!!)
             NavigationEvent.LOAD_URL -> {
                 (activity as MainActivity).onTextInputUrlEntered(value!!, autocompleteResult!!, UrlTextInputLocation.MENU)
-                setOverlayVisible(false)
+                if (value != Urls.APP_HOME) setOverlayVisible(false)
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/browser/BrowserFragment.kt]: Rather than stop this at the LOAD_URL layer, can we stop it at the input validation layer? i.e. in the commit listener, don't call load url if the URL is invalid? This seems less reactive to me and doesn't require us to try to undo state (e.g. we're recording a telemetry event for this page load).

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/focus/browser/BrowserFragment.kt]: Good point.

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 2]
```diff
@@ -70,6 +71,9 @@ enum class NavigationEvent {
         const val VAL_UNCHECKED = "unchecked"
     }
 }
+
+// TODO remove this suppression.
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: nit: inline, e.g.:
```kotlin
@Suppress("LargeClass") // #1187: we'll address this later

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 3]
```diff
@@ -238,6 +242,11 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
     private fun setupUrlInput() = with(navUrlInput) {
         setOnCommitListener {
             val userInput = text.toString()
+            if (userInput == BrowserFragment.APP_URL_HOME) {
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: Much better! Add a comment to explain why this is necessary.
