### PR TITLE
Closes #1489: print failed pocket requests

### LINKED ISSUE #1489: Failed Pocket network requests do not print their exceptions

### PR DESCRIPTION
**Pull request by Baron-Severin**
### Pull Request checklist

- [X] This PR includes thorough **tests** or an explanation of why it does not
- [X] This PR includes a **CHANGELOG entry** or does not need one
Not user facing

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/pocket/PocketEndpoint.kt [hunk 1]
```diff
@@ -51,6 +51,7 @@ object PocketEndpoint {
         if (videos.isNotEmpty()) videos else null
     } catch (e: JSONException) {
         Log.w(LOGTAG, "convertVideosJSON: invalid JSON from Pocket server")
+        e.printStackTrace()
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/pocket/PocketEndpoint.kt]: Can you include this in the `Log.w` call? It takes a Throwable.
