### PR TITLE
Closes #1109: Go back to overlay on menu click from Pocket

### LINKED ISSUE #1109: Menu press on Pocket video feed should open overlay
## Steps to reproduce
From clean start
- Open pinned site
- Click menu
- Open pocket
- Click menu

### Expected behavior
@aminalhazwani Should this go back to the main menu, or to the previously opened site?

### Actual behavior
Nothing happens

### Device information
Device: Fire Cube, smaller TV in office
Fire OS: 6.2.2.3
Commit: e0ae14e04f35f94a600385c8e34d5d62886d52c1

### PR DESCRIPTION
**Pull request by dnarcese**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt [hunk 1]
```diff
@@ -189,11 +195,12 @@ class MainActivity : LocaleAwareAppCompatActivity(), OnUrlEnteredListener, Media
                 return
             }
 
-            val currFragment = fragmentManager.findFragmentByTag(SettingsFragment.FRAGMENT_TAG)
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt]: huh, I guess that old code wasn't actually very correct, bc it only checked for the Settings fragment...
