### PR TITLE
Fixes #1083 - UITest fixes and test cleanup

### LINKED ISSUE #1083: Failing UI tests
UI Tests are currently broken.

Four compilation failures
- [ ] PinnedTileTests#testCustomPinnedTile
- [ ] TvScreenshots#defaultHomeScreen
- [ ] TvScreenshots#browserNavOverlay
- [ ] BrowserOverlayTest#testBrowserOverlay
- [ ] PageLoadTest#PageLoadTest

When these compilation failures are commented out, 11 of our 12 tests fail.

We need to go through all tests, determine whether or not each is still a valid test case, then update them.  For this story to be considered complete, all tests should compile and pass.

### PR DESCRIPTION
**Pull request by AaronMT**
- Renames BrowserOverlayTest to BrowserBFT
- UI test fixes
- Fixes Screengrabfile default
- Removes `pinTileFromOverlay` from screenshots until a less flaky solution is found, it was causing all sorts of session issues

Addresses issue #1083

### CODE REVIEW

**Comment by AaronMT** [comment]
The BFT's will pass with with https://github.com/mozilla-mobile/firefox-tv/issues/1099 fixed

File: app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java [hunk 1]
```diff
@@ -11,40 +11,40 @@
 import android.preference.PreferenceManager;
```
Comment (npark-mozilla) [inline app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java]: Can we also add test to check for "page not found" error here?  i.e. going to invalid url like "firefox:aaa" would open the dialog.

Comment (AaronMT) [reply app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java]: There's many errors, I don't know how important these are they seem low priority https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values/strings.xml

Comment (npark-mozilla) [reply app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java]: Right, this reminds me, supposedly it is using the focus string for error message, and if so we won't need to check here again.
