### PR TITLE
1916 fix back from webpage exit

### LINKED ISSUE #1916: Back to exit doesn't work from webpage
Looks like caused in a recent commit with #277 

## Steps to reproduce
Launch Firefox
Load website
Click remote Back to return to about:home/overlay
Click remote Back again

### Expected behavior
On back from about:home/overlay, app exits

### Actual behavior
Overlay toggles, doesn't exit

### Device information
* Fire TV device: Emulator 26
* Latest affected Firefox version: master 785501a9eb6c68386b84d0f1104fc5b2f19ed9cb
* Earliest affected Firefox version: master 785501a9eb6c68386b84d0f1104fc5b2f19ed9cb

### PR DESCRIPTION
**Pull request by Baron-Severin**
Closes #1916 

### Pull Request checklist

- [X] This PR includes thorough **tests** or an explanation of why it does not
- [X] This PR includes a **CHANGELOG entry** or does not need one
- [ ] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [X] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt [hunk 1]
```diff
@@ -128,13 +128,32 @@ class BasicNavigationTest {
...
     fun exitAppByBackButtonTest() {
         navigationOverlay {
             remoteBack()
             assertActivityFinishing(activityTestRule)
         }
     }
+
+    @Test
+    fun navigateThenExitAppByBackButtonTest() {
+        val server = MockWebServer().apply {
```
Comment (liuche) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt]: Since we might be using this for multiple tests in this file, I wonder if there are any savings/clarity by setting this up in one place, but a) not every test uses it, and b) since we clear app state in between test runs, I guess it doesn't matter because the server object can't persist?

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 2]
```diff
@@ -169,19 +170,21 @@ class ScreenController {
...
 
-    private fun isOnHomeUrl(fragmentManager: FragmentManager): Boolean {
-        // TODO: Would be more correct to get this from the model rather than the Fragment.
-        val webRenderFragment = fragmentManager.webRenderFragment()
-        return webRenderFragment.session.url == URLs.APP_URL_HOME
+    private fun canGoBack(): Boolean {
+        return sessionRepo.state.value?.backEnabled == true
+    }
+
+    private fun isOnHomeUrl(): Boolean {
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Good on pulling this out.

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 3]
```diff
@@ -169,19 +170,21 @@ class ScreenController {
...
+        val transition = ScreenControllerStateMachine.getNewStateMenuPress(_currentActiveScreen.value!!, isOnHomeUrl())
         return handleTransitionAndUpdateActiveScreen(fragmentManager, transition)
     }
 
-    private fun isOnHomeUrl(fragmentManager: FragmentManager): Boolean {
-        // TODO: Would be more correct to get this from the model rather than the Fragment.
-        val webRenderFragment = fragmentManager.webRenderFragment()
-        return webRenderFragment.session.url == URLs.APP_URL_HOME
+    private fun canGoBack(): Boolean {
+        return sessionRepo.state.value?.backEnabled == true
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: It's good to gate this on back stack - one thing this does do is add another layer on top of the `canGoBackTwice` which still bothers me, but that's a bigger fix (and depends on https://github.com/mozilla-mobile/android-components/issues/1993)

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/androidTest/java/org/mozilla/tv/firefox/ui/BasicNavigationTest.kt]: I think we'd ideally just have a really nice helper that sets things up, but we've tried that and, to be perfectly honest, I think we've landed on a state where it's just confusing.  The requirements are a little bit different between each test.  I haven't really figured out how I want this to work, but I share your concerns.

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt (hunk 3 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: I think it should be roughly independent of `canGoBackTwice`, right?  Regardless of how we calculate when the back button is enabled, once it's not we should exit the app.  To me that seems like a relatively generic seam.
