### PR TITLE
Closes #1830: fixes YouTube focus when overlay is open

### LINKED ISSUE #1830: Overlay can break YouTube navigation
## Steps to reproduce
- From home screen (does not have to be a fresh install)
- Click YouTube tile
- Immediately reopen overlay with menu button
- Wait for YouTube to finish loading
- Close overlay

### Expected behavior
- YouTube should operate as normal

### Actual behavior
- Focus movement, clicks, and back presses do nothing
- Menu button still works
- Reloading page fixes this

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 65ad45e6be65136aee2f2885c5e0556504759f8c
* Earliest affected Firefox version: ?

### PR DESCRIPTION
**Pull request by Baron-Severin**
RCA:
There is a WebView bug that, when the WV loses and regains focus, causes the incorrect DOM element to receive focus (https://bugs.chromium.org/p/chromium/issues/detail?id=826577). Our workaround for this caches the currently focused view on overlay open, then focuses it on overlay close. When we open the overlay during a loading screen, we cache the body element. The overlay is then closed, and the body element focused, rather than the view on which YouTube has programmatically requested focus.

Fix:
Instead of caching focus on overlay open, this now caches it just before overlay close.  This allows us to use the most recently focused DOM element.

### Pull Request checklist

- [X] This PR includes thorough **tests** or an explanation of why it does not
Testing this will involve writing a complex Espresso test.  This is out of scope for this story, but https://github.com/mozilla-mobile/firefox-tv/issues/1832 was opened
- [X] This PR includes a **CHANGELOG entry** or does not need one
- [X] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [X] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 1]
```diff
@@ -212,6 +213,7 @@ class ScreenController {
                     .hide(fragmentManager.pocketFragment())
                     .hide(fragmentManager.settingsFragment())
                     .commitNow()
+                fragmentManager.webRenderFragment().onShowEngineView()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: We're adding `onShowEngineView` each time currentActiveScreen is assigned to WEB_RENDER: this approach is fragile because if the code changes and we have a new assignment, we may forget to add this line.

What if we were reactive and did it as an observer instead? Do the LiveData observers get called before the View focus changes? If not, could we write a small wrapper around the currentActiveScreen update so that our observer can get called first before the LiveData changes?

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 2]
```diff
@@ -211,4 +212,11 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
         }
         return false
     }
+
+    /**
+     * Called before the [EngineView] is shown
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: -> Must be called...

File: app/src/system/java/org/mozilla/tv/firefox/ext/EngineView.kt [hunk 3]
```diff
@@ -39,14 +39,7 @@ fun EngineView.setupForApp() {
...
-        if (!hasFocus) {
-            // For why we're modifying the focusedDOMElement, see FocusedDOMElementCacheInterface.
-            //
-            // Any views (like BrowserNavigationOverlay) that may clear the cache, e.g. by
-            // reloading the page, are required to handle their own caching. Here we'll handle
-            // cases where the page cache isn't cleared.
-            focusedDOMElement.cache()
-        } else {
+        if (hasFocus) {
             // Trying to restore immediately doesn't work - perhaps the WebView hasn't actually
```
Comment (mcomella) [inline app/src/system/java/org/mozilla/tv/firefox/ext/EngineView.kt]: You should preface this comment with, "// For why we're modifying the focusedDOMElement, see FocusedDOMElementCacheInterface."

Also, we may want to mention that cache the element is done elsewhere.

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 4]
```diff
@@ -211,4 +212,11 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
...
+     */
+    fun onShowEngineView() {
+        engineView?.focusedDOMElement?.cache()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: We need to explain why we cache here and specifically here. Basically, the gist of your commit summary (cache the element at the last possible second) should really be in the code base as comments instead.

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: That's a good point.  The LiveData observers are called synchronously when the value is set, and asynchronously when post is used.  Changing these to set the value before kicking off the transaction would be trivial, but I'll have to double check that it won't have negative effects.

Good catch.

File: CHANGELOG.md [hunk 5]
```diff
@@ -15,6 +15,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - Fixed links on settings About page that did not load (#1731)
 - A memory leak (#1628)
 - Fixed bug that could cause YouTube to display vertically offset from where it should be (#1719)
+- Bug that could cause YouTube to lose focus if the overlay was opened during loading (#1830)
```
Comment (mcomella) [inline CHANGELOG.md]: Has this been seen by users yet? If not, we don't need a changelog item for it.

Comment (mcomella) [inline CHANGELOG.md]: nit: -> "YouTube to be unresponsive"

Users don't know what losing focus means. :)

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 6]
```diff
@@ -170,49 +171,49 @@ class ScreenController {
         // Call show() before hide() so that focus moves correctly to the shown fragment once others are hidden
         when (transition) {
             Transition.ADD_OVERLAY -> {
-                fragmentManagerShowNavigationOverlay(fragmentManager, true)
                 _currentActiveScreen.value = ActiveScreen.NAVIGATION_OVERLAY
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Add a comment (maybe above `when`, next to first currentActiveScreen assignment, or wrap currentActiveScreen assignment and comment in that method) that we need to update the active screen before we perform the fragment transactions so this behavior that we rely on doesn't regress.

Can we add a test for this?

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 7]
```diff
@@ -27,9 +27,10 @@ import org.mozilla.tv.firefox.widget.InlineAutocompleteEditText
 
 class ScreenController {
 
-    private var _currentActiveScreen = MutableLiveData<ActiveScreen>().apply {
+    private val _currentActiveScreen = MutableLiveData<ActiveScreen>().apply {
         value = ActiveScreen.NAVIGATION_OVERLAY
     }
+    // This is updated just before the fragment transaction is committed
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: nit: use property kdoc rather than "//": that indicates the comment is for consumers rather than file private comments.

Also, the comment should be more explicit, "Observers will be notified just before the fragment transaction is committed."

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 8]
```diff
@@ -135,8 +135,13 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
          *  memory leak while clearing data. See [WebViewCache.clear] as well as #1720
          */
         serviceLocator?.screenController?.currentActiveScreen?.observe(viewLifecycleOwner, Observer {
-            if (it != ScreenControllerStateMachine.ActiveScreen.WEB_RENDER) {
-                engineView.pauseAllVideoPlaybacks()
+            when (it) {
+                // Cache focused DOM element just before WebView gains focus. See comment in
+                // FocusedDOMElementCacheInterface for details
+                ScreenControllerStateMachine.ActiveScreen.WEB_RENDER -> engineView.focusedDOMElement.cache()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: nit: -> `ActiveScreen.WEB_RENDER` to make this slightly more readable.

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 9]
```diff
@@ -135,8 +135,13 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
          *  memory leak while clearing data. See [WebViewCache.clear] as well as #1720
          */
         serviceLocator?.screenController?.currentActiveScreen?.observe(viewLifecycleOwner, Observer {
-            if (it != ScreenControllerStateMachine.ActiveScreen.WEB_RENDER) {
-                engineView.pauseAllVideoPlaybacks()
+            when (it) {
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: nit: I think this is more readable as an if statement because the comparison (`it == WEB_RENDER`) is on a single line.

File: CHANGELOG.md (hunk 5 above)
Comment (mcomella) [inline CHANGELOG.md]: nit: commit message: what changelog is being updated?

File: app/src/main/java/org/mozilla/tv/firefox/webrender/FocusedDOMElementCacheInterface.kt [hunk 10]
```diff
@@ -17,6 +17,10 @@ import android.view.View
  * to restore the focused element, dpad navigation is entirely broken (#393): that is
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/FocusedDOMElementCacheInterface.kt]: nit: commit message: which comments are improved?

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt (hunk 6 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: This does seem like a good thing to test, but it's not clear to me at the moment how.  Do you have any suggestions?

**Comment by liuche** [comment]
@Baron-Severin can you open a PR for this against the 3.4.1-LAT2 branch? Then we can send out a LAT and if everything seems fixed, push a release to Amazon.

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt (hunk 6 above)
Comment (mcomella) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: First thought: if somehow you could stub `setCurrentActiveScreen` and `fragmentManagerShowNavigationOverlay`, you can have each toggle a boolean flag and check that the other boolean flag is in the appropriate state. It seems obnoxious to decouple these invocations so heavily, however.
