### PR TITLE
Closes #750, Issue #1628: Move Sentry init to application

### LINKED ISSUE #750: Sentry: consider moving init to Application
e.g. we're missing crash reporting for OnboardingActivity

The docs put it in an Activity but that would require multiple inits and it seems fine to put it in application since it uses the applicationContext.

### PR DESCRIPTION
**Pull request by mcomella**
We verified with the Sentry team that this is an acceptable way to
initialize Sentry.

This change is beneficial because:
- It fixes a memory leak (not completely though: there are still things to follow-up on)
- It allows all Activites to get crash reporting
- We get crash reporting earlier in the init process

It's concerning because:
- we're modifying crash reporting code
- Sentry is slow to start up so this may further affect startup time

This change could be better if:
- We could initialize Sentry before the ServiceLocator is initialized
and before the PreferenceManager default values get set

I verified this change was working correctly by adding code to crash the
app (throw when M key is pressed) and ensuring the events were received
by the server. I also tested events are not received by the server when
data collection is disabled.

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
  - No real issues fixed for users
- [x] The **UI tests** are passing after this PR (`./gradlew connectedDebugAndroidTest`)
  - #1700 is a known failure
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/telemetry/SentryIntegration.kt [hunk 1]
```diff
@@ -28,8 +30,20 @@ import org.mozilla.tv.firefox.ext.serviceLocator
...
-        context.serviceLocator.settingsRepo.dataCollectionEnabled.observeForever { isEnabled ->
+
+    @VisibleForTesting(otherwise = NONE)
+    var isInit = false
+        private set
+
+    /**
+     * Initializes Sentry. This method should only be called once.
+     */
+    fun init(appContext: Context, serviceLocator: ServiceLocator) {
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/telemetry/SentryIntegration.kt]: If we only need the locator for the `SettingsRepo`, could we pass that instead of the `ServiceLocator`?
