### PR TITLE
Fixes #1159: catches telemetry lifecycle crash

### LINKED ISSUE #1159: Fatal exception on out of order Telemetry events
See https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4270217/

We are seeing ~250 crashes per day on v2.1 due to `TelemetryWrapper#stopSession` being called before `TelemetryWrapper#startSession`.  This implies that, on some small number of device/OS combinations, `MainActivity#onPause` is being called before `MainActivity.onResume`.

### PR DESCRIPTION
**Pull request by Baron-Severin**
Blocked until we integrate the next A-C release.  Otherwise finished.

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt [hunk 1]
```diff
@@ -162,7 +122,15 @@ object TelemetryWrapper {
 
     @UiThread // via TelemetryHomeTileUniqueClickPerSessionCounter
     fun stopSession(context: Context) {
-        TelemetryHolder.get().recordSessionEnd()
+        fun sendEndSessionFailedEvent() {
+            // In rare instances, we have seen stopSession called before startSession.
+            // It is unknown at this time how this happens, but it is very infrequent
+            // so we are logging the event and otherwise dropping the error
+            // See https://bugzilla.mozilla.org/show_bug.cgi?id=1405192
+            TelemetryEvent.create(Category.ERROR, Method.ONPAUSE_CALLED_BEFORE_ONRESUME, Object.APP).queue()
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: Alternatively, I think we can record events in Sentry that include a stack trace.

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+    @Before
+    fun setup() {
+        val telemetry = TelemetryFactory.createTelemetry(RuntimeEnvironment.application)
+        telemetrySpy = spy(telemetry)
+        TelemetryHolder.set(telemetrySpy)
+    }
+
+    @Test
+    fun `WHEN session events are called on TelemetryWrapper THEN associated Telemetry methods should be called`() {
```
Comment (mcomella) [inline app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt]: nit: which session events? Which Telemetry methods are expected to be called?

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+        TelemetryWrapper.stopSession(RuntimeEnvironment.application)
+        verify(telemetrySpy, times(1)).recordSessionStart()
+        verify(telemetrySpy, times(1)).recordSessionEnd(any())
+    }
+
+    /**
+     * See comment in [TelemetryWrapper.stopSession]
+     */
+    @Test
+    fun `WHEN TelemetryWrapper is called out of order THEN we should not crash`() {
```
Comment (mcomella) [inline app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt]: Should we additionally verify:
- when stopSession is called multiple times in a row (e.g. in theory, could happen in real world).
- That we create a telemetry event when this happens?

**Comment by mcomella** [comment]
@Baron-Severin Please fill out [a data request review form](https://github.com/mozilla/data-review/blob/master/request.md) and update the telemetry documentation!

**Comment by Baron-Severin** [comment]
@liuche 
# Request for data collection review form

1) What questions will you answer with this data?

* How frequently does our session start / session end code fail to run properly?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?

* We need to swallow these exceptions to prevent a crash, but should be able to keep an eye on how often this is failing.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

* There is no other way to see how frequently this code fails.

4) Can current instrumentation answer these questions?

* No existing telemetry exists to serve this need.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

| Event                                    | category | method     | object                   | value |
|------------------------------------------|----------|------------|-----------|---------------|
| onPause called before onResume               | error   | pause_before_resume       | app         |  |


6) How long will this data be collected?  Choose one of the following:

* Permanently (Barbara Bermes)

7) What populations will you measure?

* All users

8) If this data collection is default on, what is the opt-out mechanism for users?

* Users may opt out of data collection by turning off data collection from the settings menu.

9) Please provide a general description of how you will analyze this data.

* If we see this number increase significantly, we will have to rework our session code to allow for this framework lifecycle bug.

10) Where do you intend to share the results of your analysis?

* On re-dash and with mobile teams.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: @liuche do you know how we can do that?

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt (hunk 3 above)
Comment (Baron-Severin) [reply app/src/test/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.kt]: Hm.  I can see how startSession could theoretically be called twice in a row (and I'll add that case), but I'm not sure how stopSession could be.

I'll check that telemetry events are being sent in this case too.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt (hunk 1 above)
Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: You'll probably have to look in the Sentry docs and potentially try out some methods to see which just send String text and which might send stacktraces.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt [hunk 4]
```diff
@@ -113,43 +104,12 @@ object TelemetryWrapper {
...
-            val serializer = JSONPingSerializer()
-            val storage = FileTelemetryStorage(configuration, serializer)
-            val client = HttpURLConnectionTelemetryClient()
-            val scheduler = JobSchedulerTelemetryScheduler()
-
-            TelemetryHolder.set(Telemetry(configuration, storage, client, scheduler)
-                    .addPingBuilder(TelemetryCorePingBuilder(configuration))
-                    .addPingBuilder(TelemetryMobileEventPingBuilder(configuration))
-                    .setDefaultSearchProvider(createDefaultSearchProvider(context)))
+            TelemetryHolder.set(TelemetryFactory.createTelemetry(context))
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: > typealias TelemetryEntryPoint = Telemetry and make the factory based on that. EntryPoint isn't a great name so maybe something better.

I think having global typealiases seems like it could get confusing.  I would rather try to open a PR against A-C that changes the class name itself.
> TelemetryHolder -> TelemetryProvider (more conventional)

Unfortunately this is part of A-C.
> TelemetryWrapper -> TelemetryIntegration (to better distinguish from Holder/Provider)

Agreed, and done.

> could also try putting TelemetryWrapper behind a module so the only thing exposed to the app is TelemetryIntegration, simplifying this problem.

Although I haven't needed to yet, keeping TelemetryFactory available and using it in our Application to assemble TelemetryIntegration allows us to substitute in different values for testing.  I think that's worth preserving.

**Comment by liuche** [comment]
unassigning myself from review now that this bug doesn't require data review and is using Sentry to send a stacktrace instead.

File: app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt [hunk 5]
```diff
@@ -0,0 +1,22 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+package org.mozilla.focus.utils
+
+import org.mockito.Mockito
+
+/**
+ * A normal [Mockito.any] is a nullable type, so this allows us to test nonnull
```
Comment (mcomella) [inline app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt]: You should mention that the reason this is required is because it crashes otherwise, i.e. "use this when `any()` crashes".

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+import org.robolectric.RobolectricTestRunner
+import org.robolectric.RuntimeEnvironment
+import org.robolectric.annotation.Config
+
+class NoTelemetryApplication : FocusApplication() {
+    override fun initTelemetry() {}
+}
+
+@RunWith(RobolectricTestRunner::class)
+@Config(application = NoTelemetryApplication::class)
```
Comment (mcomella) [inline app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt]: I realized that robolectric could, but highly improbably, be uploading telemetry data: I filed https://github.com/mozilla-mobile/firefox-tv/issues/1300

**Comment by Baron-Severin** [comment]
@mcomella I changed my approach considerably, the changes should be a lot less invasive now.  Ready for re-review.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryIntegration.kt [hunk 7]
```diff
@@ -97,16 +98,15 @@ object TelemetryWrapper {
 
     // Available on any thread: we synchronize.
     private val pocketUniqueClickedVideoIDs = Collections.synchronizedSet(mutableSetOf<Int>())
+    private lateinit var sentryWrapper: SentryWrapper
 
     @JvmStatic
-    fun init(context: Context) {
+    fun init(sentryWrapper: SentryWrapper, telemetry: Telemetry) {
+        this.sentryWrapper = sentryWrapper
         // When initializing the telemetry library it will make sure that all directories exist and
```
[the remark this answers is not in the document]
Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/telemetry/TelemetryIntegration.kt]: I meant that `//` comments typically have a new line above them:
```kotlin
fun init(sentryWrapper: SentryWrapper, telemetry: Telemetry) {
        this.sentryWrapper = sentryWrapper

        // When initializing the telemetry library
```

GitHub comments give context above the line the author comments on so I was commenting specifically on the `//` comment line.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryIntegration.kt [hunk 8]
```diff
@@ -41,8 +33,13 @@ private const val KEY_CLICKED_HOME_TILE_IDS_PER_SESSION = "clickedHomeTileIDsPer
...
         "LargeClass"
 )
-object TelemetryWrapper {
-    private const val TELEMETRY_APP_NAME_FOCUS_TV = "FirefoxForFireTV"
+open class TelemetryIntegration protected constructor(
+    private val sentryIntegration: SentryIntegration = SentryIntegration
+) {
+
+    companion object {
+        val INSTANCE: TelemetryIntegration by lazy { TelemetryIntegration() }
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/telemetry/TelemetryIntegration.kt]: I don't love that we have to do this but it looks like the best of all of our options:
- (old solution) Top-level object with static `init()`: can't replace the instance under testing; strange mechanics when testing the object
- Give TelemetryIntegration instance to Application to own: need context to add telemetry

File: app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt [hunk 9]
```diff
@@ -50,6 +50,39 @@ object SentryWrapper {
...
+     *      }
+     *  }
+     *
+     * [Sentry] has a private constructor, disallowing this pattern, so instead we delegate
+     * [SentryIntegration.capture] to [Sentry.capture]. By injecting [SentryIntegration] into
+     * classes that we test, we can now verify that this method is being called in our tests.
+     *
+     * See [TelemetryIntegrationTest.setup] for an example.
+     */
+    internal fun capture(exception: Exception) {
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: nit: internal isn't doing anything here, right?

File: app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt [hunk 10]
```diff
@@ -50,6 +50,39 @@ object SentryWrapper {
         // they're personally identifiable information.
         Sentry.getContext().user = SentryUnknownUser()
     }
+
+    /**
+     * One way to test calls to static methods is to pass instances of their objects into the
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: See my other comment about the first line of kdoc comments.

In general, this comment seems unrelated to what the method does so is inappropriate for kdoc. In situations like these, prefer comments that are not exposed in API documentation, like `//`. (we generally don't use `/*` comments).

File: app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt [hunk 11]
```diff
@@ -50,6 +50,39 @@ object SentryWrapper {
...
+     *      @Test
+     *      fun testSimpleClass() {
+     *          val spy = spy(Singleton)
+     *          val simpleClass = SimpleClass(spy)
+     *          simpleClass.testThis()
+     *          verify(spy).callMethod()
+     *      }
+     *  }
+     *
+     * [Sentry] has a private constructor, disallowing this pattern, so instead we delegate
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: Another reason we force everyone to go through `SentryIntegration` (same for Telemetry) is modularity: if we need to swap out the implementation of the Integration class, consumers can make the same calls. No one in the app code should know about `Sentry`, just `SentryIntegration`.

Since this is the primary reason for having SentryIntegration, I don't think this comment is necessary.

I don't know where to comment about why we do these `Integration` classes like that – maybe a README in an `integrations` package?

**Comment by mcomella** [comment]
that is, lgtm w/ nits. Thanks for improving our testing story too!

File: app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt [hunk 12]
```diff
@@ -0,0 +1,21 @@
...
+/**
+ * Use this when [Mockito.any] crashes.
+ *
+ * A normal [Mockito.any] is a nullable type, so this allows us to test nonnull
+ * code.
+ *
+ * Taken from https://medium.com/@elye.project/befriending-kotlin-and-mockito-1c2e7b0ef791
+ */
+@Suppress("UNCHECKED_CAST")
+fun <T> anyNonNull(): T {
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt]: Unfortunately no.  This is weird, but take a look at `org.mockito.ArgumentMatchers#notNull`.  It produces a side effect that somehow results in the test passing, but actually returns `null`.  This causes Kotlin's null checks to throw an exception.

File: app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt [hunk 13]
```diff
@@ -0,0 +1,21 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/test/java/org/mozilla/focus/utils/AnyNonNull.kt]: Makes sense to me.

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt [hunk 14]
```diff
@@ -0,0 +1,64 @@
...
+    private lateinit var telemetrySpy: Telemetry
+    private lateinit var sentrySpy: SentryIntegration
+
+    @Before
+    fun setup() {
+        val telemetry = TelemetryFactory.createTelemetry(RuntimeEnvironment.application)
+        telemetrySpy = spy(telemetry)
+        TelemetryHolder.set(telemetrySpy)
+        sentrySpy = spy(SentryIntegration)
+        telemetryIntegration = TestTelemetryIntegration(sentrySpy)
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt]: `TelemetryIntegration` has a protected constructor, so the rest of the app isn't able to pass `Sentry` values to it.  If we relaxed that visibility, then we wouldn't need the subclass.  I don't strongly prefer either method, what would your preference be?

File: app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt (hunk 11 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: Hm.  I'm not sure if we need to include this in the project at all, now that you mention it.  What do you think about adding a page in our shared documentation repo?  I could take the time to write one.

Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: Good idea. Maybe we should link to it from each of the `Integration` pages, just so it's not overlooked? Like:
```
/* License
 */

// See <url> for dependency integration best practices.

class TelemetryIntegration {

File: app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt (hunk 14 above)
[the remark this answers is not in the document]
Comment (mcomella) [reply app/src/test/java/org/mozilla/focus/telemetry/TelemetryIntegrationTest.kt]: Ah, I didn't notice that. `protected` constructor sounds better to me. No need to add comments on the `Test*` then: I think it's a known pattern.

File: app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt (hunk 11 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/focus/telemetry/SentryIntegration.kt]: I've made a note to myself to write it, and I'll open a new PR adding the link once it's done.
