### PR TITLE
Closes #885: Follow-up: Toast for "Unpin" hint is not shown according…

### LINKED ISSUE #885: Follow-up: Toast for "Unpin" hint is not shown according to spec
Follow-up from #782 
### Steps to reproduce
* Open Firefox TV
* Go to home screen

### Expected behavior
* Toast hint shows up when tile is selected, max 3 times

### Actual behavior
* Toast hint shows up over Turbo mode screen
* Toast doesn't show up when navigating through tiles

### Device information

* Fire TV device: 25
* Firefox version: master

### PR DESCRIPTION
**Pull request by bkmunar**
… to spec

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 1]
```diff
@@ -135,7 +136,16 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
                     onNavigationEvent?.invoke(NavigationEvent.LOAD_TILE, urlStr, null)
                 }
             }
-        }, onTileLongClick = openHomeTileContextMenu)
+        }, onTileLongClick = openHomeTileContextMenu, onTileFocused = {
+            val prefInt = PreferenceManager.getDefaultSharedPreferences(context).getInt(SHOW_UNPIN_TOAST_COUNTER_PREF, 0)
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: Hm, I guess this shows the toast 3 times on a single launch. I don't think that really makes sense - probably my fault for not being entirely clear "when tile is first selected on a launch, max 3 times".

The approach to use sharedprefs seems fine, but let me clarify this behavior in the bug.

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 2]
```diff
@@ -135,7 +136,16 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
...
+            if (prefInt < 2) {
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: This 2 should be a constant so that it's named, like MAX_UNPIN_TOAST_COUNT, rather than just a random 2 in the code.

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt (hunk 1 above)
Comment (liuche) [reply app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: Can you add a constant that gets set once per launch, maybe in `initTiles`, or in one of the `onCreate*`?

**Comment by liuche** [comment]
@bkmunar how do you know this works? Can you describe why you think this change works? What situations did you test in, and does that cover all the expected cases?

**Comment by bkmunar** [comment]
Well I have tested that the toast only shows up either once per launch or after clearing the history. This is because initTiles() (and the init function for the BrowserNavigationOverlay for that matter) is instantiated in those two cases. I think this is appropriate behavior for this feature (although there may be a discussion if it should happen after clearing history. I think it's ok, but I think making it happen once per launch would involve another pref).

**Comment by liuche** [comment]
@bkmunar since the overlay shows up in two instances (launch, opening the overlay), did you test that behavior, and what did you see? Does it behave the way you'd expect it to?

(To be clear, I'm not asking these questions to be challenging - the goal is to make sure that the code is behaving correctly, and part of that is understanding how it behaves in all the cases where it's used and making sure it's what we expect. So in this case, I'd expect you to test all the cases, and raise any questions you have.)

**Comment by bkmunar** [comment]
It seems to work fine in both those cases. After launch and user focuses on a tile for the first time, one toast shows up. After navigation to a site and overlay is pulled up, the toast shows up depending on if we've shown the toast already or not.

**Comment by bkmunar** [comment]
I did notice that the BNO init() is called after viewing the Pocket feed thus making the toast triggerable again. Not sure if this is what we want, but if not, I think we should resort to a pref that is changed every time the app is created/destroyed if we really want the behavior to be specific.

File: app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt [hunk 3]
```diff
@@ -77,6 +81,8 @@ class BrowserNavigationOverlay @JvmOverloads constructor(
      */
     var uiLifecycleCancelJob: Job
 
+    var canShowUpinToast: Boolean = false
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt]: Nit: add a comment here about why we have this.
