### PR TITLE
Closes #1824: Fix internal url obstruction in gv

### LINKED ISSUE #1824: Gecko build "about:home" is broken on launch
## Steps to reproduce
- Select "geckoDebug" build variant
- Run and open the FFTV app

### Expected behavior
- Overlay opens with `about:home` loaded in the url bar

### Actual behavior
- Overlay opens with `data:text/html,<html></html>` in the url bar

### PR DESCRIPTION
**Pull request by psymoon**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [ ] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/utils/UrlUtils.kt [hunk 1]
```diff
@@ -158,8 +158,11 @@ object UrlUtils {
      */
     @JvmStatic
     fun toUrlBarDisplay(url: String): String {
-        return when (url) {
-            URLs.APP_URL_HOME -> "" // Empty string forces the EditText to show hint text
+        return when {
+            url == URLs.APP_URL_HOME -> "" // Empty string forces the EditText to show hint text
+            // GeckoView loads [data: url] when RequestInterceptor.InterceptionResponse.Content()
+            // due to lack of internal page api (bug #1535131)
+            url.startsWith("data:", false) -> ""
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/utils/UrlUtils.kt]: Hm, it looks like from bug 1535131, this means that the url will actually just show the hint, but not any sort of "firefox:about" url? I guess that's fine for this workaround.
From the discussion though, it looks like this isn't high enough priority for GeckoView to fix because it'll be a non-trivial amount of work, so our "about:" pages in GV Firefox will just show the hint - heads up @athomasmoz is that fine?

Comment (athomasmoz) [reply app/src/main/java/org/mozilla/tv/firefox/utils/UrlUtils.kt]: Agreed. This sounds fine to me
