### PR TITLE
Closes #1572: Close app on back button press

### LINKED ISSUE #1572: Can't exit app with back-button press
## Steps to reproduce
Open app.
Click back button on remote.

### Expected behavior
Exits app.

### Actual behavior
Doesn't exit app, no feedback.

### PR DESCRIPTION
**Pull request by dnarcese**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 1]
```diff
@@ -347,8 +347,6 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
                 TelemetryIntegration.INSTANCE.browserBackControllerEvent()
             }
             else -> {
-                context!!.webRenderComponents.sessionManager.remove()
-
                 // We can get into this state in two situations:
                 // - (1) The user is on the "home page" and the overlay is visible. In this situation we just want to
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: I don't think that we want this (2) case anymore - looking at the history this was written a long time ago, before we had the combined overlay/home tiles. That's what's probably actually breaking this (because it's returns true) - and the true was a result of fixing an auto-kotlin-convert: https://github.com/mozilla-mobile/firefox-tv/blame/8c61df2e2f4fe2678418314accb9e31a79d4a00b/app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt#L366
If the overlay is not visible and we're on a website, we should just exit, not open the overlay. It actually looks like we should just return false for this whole `else` statement of the when/else, and remove the `if !browserOverlay.isVisible` check. That should fix it because it'll allow the app to handle the back button press.

File: app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt [hunk 2]
```diff
@@ -193,7 +193,7 @@ class MainActivity : LocaleAwareAppCompatActivity(), OnUrlEnteredListener, Media
                 // The Browser fragment handles back presses on its own because it might just go back
                 // in the browsing history.
                 return
-            }
+            } else finish()
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/MainActivity.kt]: Looking at the below code, if we remove the
```
if (!browserOverlay.isVisible) {
    // If the browser overlay is not visible then we show it now immediately. Depending on the loading
    // state of the page we m
    setOverlayVisible(true)
```
is this still necessary, or does the Activity handle the back behavior correctly?

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt (hunk 1 above)
Comment (dnarcese) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: Oh yup, this is a much simpler fix!
