### PR TITLE
1927 fix youtube menu back

### LINKED ISSUE #1927: Back/forward buttons in overlay do not work on YouTube TV
## Steps to reproduce
- Open app
- Click Youtube tile
- open video
- open overlay
- hit back

### Expected behavior
Youtube goes back to homepage

### Actual behavior
Youtube stays on the current video

### Device information
* Fire TV device: Stick gen 2
* Latest affected Firefox version: latest, v3.4.1-lat1?
* Earliest affected Firefox version: ?

I cannot reproduce this issue when using the hardware back button.

### PR DESCRIPTION
**Pull request by Baron-Severin**
Closes #1927 
Depends on #1939 

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
I tried to get this under test for hours, but ran into issues on the edge of A-C.  I'm going to have to think about SessionRepo for a while and come back to it. See https://github.com/Baron-Severin/firefox-tv/pull/3
- [X] This PR includes a **CHANGELOG entry** or does not need one
- [X] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

**Comment by Baron-Severin** [comment]
Merging this is blocked on https://github.com/mozilla-mobile/firefox-tv/issues/1939, but the code is ready for review.

File: app/src/main/java/org/mozilla/tv/firefox/session/SessionRepo.kt [hunk 1]
```diff
@@ -34,9 +38,16 @@ class SessionRepo(
...
 
+    enum class Event {
+        YouTubeBack, ExitYouTube
+    }
+
     private val _state = MutableLiveData<State>()
     val state: LiveData<State> = _state
 
+    private val _events: Subject<Event> = PublishSubject.create()
+    val events = _events.hide()
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/session/SessionRepo.kt]: Okay, so you `hide()` here to prevent others from calling operations like `next()` on `_events`? What's the scope of that restriction, e.g. this class, and is it redundant because `_events` is private to the class anyway? (I guess it seems like good hygiene in any case.)
And no one can just call `events.onNext` because it's just an Observable, not an ObservableSource.

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 2]
```diff
@@ -155,13 +161,21 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
...
+            }.forceExhaustive
+        }.addTo(compositeDisposable)
     }
 
     override fun onStop() {
         super.onStop()
 
         serviceLocator!!.sessionRepo.exitFullScreenIfPossible()
         sessionFeature?.stop()
+        compositeDisposable.clear()
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: Is it better to clear the compositeDisposable in bulk (like here in `onStop`) vs as we receive each event?

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt [hunk 3]
```diff
@@ -70,7 +70,7 @@ class ToolbarViewModel(
 
     @UiThread
     fun backButtonClicked() {
-        sessionRepo.exitFullScreenIfPossibleAndBack()
+        sessionRepo.attemptBack(forceYouTubeExit = true)
```
Comment (liuche) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt]: What if the user wants to go back through the YT history stack? e.g. they have watched a series of videos. (Though maybe this is already the behavior now...)
But this is a weird case - e.g. we want to handle web browsing history, but not trigger things like the "back" cursor movement.
What do you think?

**Comment by liuche** [comment]
(Sorry for the delay and maybe the over-detailed Rx review/questions - it seemed like a good opportunity to get some Rx learning in so I took it!)

File: app/src/main/java/org/mozilla/tv/firefox/webrender/YouTubeBackHandler.kt [hunk 4]
```diff
@@ -30,15 +30,14 @@ class YouTubeBackHandler(private val engineView: EngineView?, private val activi
     private val preYouTubeIndexHistory: MutableList<Int> = mutableListOf()
     private var currentPreYouTubeIndex: Int? = null
 
-    fun handleBackClick(event: KeyEvent) {
+    fun handleBackClick() {
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/YouTubeBackHandler.kt]: This comes from `Activity#onBackPressed`.  Do you think I should rename it to `onBackPressed` to better communicate that?

File: app/src/main/java/org/mozilla/tv/firefox/webrender/YouTubeBackHandler.kt [hunk 5]
```diff
@@ -68,10 +67,10 @@ class YouTubeBackHandler(private val engineView: EngineView?, private val activi
         }
     }
 
+    fun goBackBeforeYouTube() = engineView!!.handleYoutubeBack(getIndexToGoBackTo())
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/YouTubeBackHandler.kt]: The param is nullable, but looking more closely it probably shouldn't be, since the whole class won't function without it.  I'm going to give some thought to how to fix that.

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt [hunk 6]
```diff
@@ -155,13 +161,21 @@ class WebRenderFragment : EngineViewLifecycleFragment(), Session.Observer {
         super.onStart()
 
         sessionFeature?.start()
+        serviceLocator!!.sessionRepo.events.subscribe {
+            when (it) {
+                SessionRepo.Event.YouTubeBack -> youtubeBackHandler.handleBackClick()
+                SessionRepo.Event.ExitYouTube -> youtubeBackHandler.goBackBeforeYouTube()
+                null -> return@subscribe
```
[the remark this answers is not in the document]
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: It can't, but the compiler doesn't believe me (frustratingly, nullability annotations are inconsistently applied in RxJava).  Maybe I should add a comment about that.

File: app/src/main/java/org/mozilla/tv/firefox/session/SessionRepo.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/session/SessionRepo.kt]: Code local to the class can still push values through `_events`, but anything else only has access to the read-only `events`.  This is similar to what we were doing before (with `val events: LiveData<T> = _events`, see `SessionRepo.events`), but with the upside that `Observables` obtained using `.hide()` cannott be cast back to subjects (`LiveData` can be cast back and forth freely at any time).

File: app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt (hunk 2 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt]: `Disposable` is equivelent to a coroutine `Job`, so it doesn't hold references to passed events.  Instead, `compositeDisposable.clear()` is basically `List<Job>.forEach { it.cancel() }`

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt (hunk 3 above)
Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt]: I _think_ that's handled by YouTube using the ESC key, but I'll verify that before merging.

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt]: > I think that's handled by YouTube using the ESC key, but I'll verify that before merging.

It looks like this is true.  It is interesting to note that, if you've watched a bunch of videos, back will still just take you to YouTube TV home.  But that's really Google's decision.
