### PR TITLE
Closes #1832: YouTube navigation UI test

### LINKED ISSUE #1832: Write YouTube navigation UI test
YouTube is core functionality for our product, and it's important that it consistently functions.  It is, however, difficult to test, and has therefore regressed several times in the past (most recently in #1830).

Since we cannot unit test YouTube, or mock out its implementation, an Espresso test will have to be written that makes actual network calls.  This will be slow and potentially flakey, but given how important the site is and the potential for regression, it's probably worth doing.

Test should verify that:

- [x] ~~Clicking on the YouTube tile, opening the overlay, waiting for loading to end, then closing the overlay does not disrupt navigation~~
This is currently not possible with the `SessionLoadedIdlingResource`, as it will not allow the overlay to open until the page has finished loading. Opened #1892
- [x] D-pad navigation works
- [x] Hardware back cycles focus until the sidebar is focused, and then opens the overlay

### LINKED ISSUE #1892: Investigate how to write YouTube test for issue #1830
As part of #1832, one test case is 
"Clicking on the YouTube tile, opening the overlay, waiting for loading to end, then closing the overlay does not disrupt navigation"
But this is currently not possible with the `SessionLoadedIdlingResource`, as it will not allow the overlay to open until the page has finished loading. 
To not block on the other tests getting merged, opening a separate issue for this specific test case.

### PR DESCRIPTION
**Pull request by dnarcese**
Closes #1832 
Closes #1892 

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt [hunk 1]
```diff
@@ -34,7 +34,7 @@ class MainActivityTestRule(
      * implementation changes and the tests break. In that case, this code might be
      * broken because it's not used, and thus tested, at present.
      */
-    private lateinit var loadingIdlingResource: SessionLoadedIdlingResource
+    lateinit var loadingIdlingResource: SessionLoadedIdlingResource
```
Comment (psymoon) [inline app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt]: `@VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)`? :)

**Comment by dnarcese** [comment]
Test will fail until #1939 is fixed.

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt]: TBH, I would argue that we don't need the annotation at all.  This file is in the `androidTest` directory, so it isn't available from anywhere but in our tests.

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt [hunk 2]
```diff
@@ -25,9 +26,20 @@ class SessionLoadedIdlingResource : IdlingResource {
 
         val session = sessionManager.selectedSession
 
+        /**
+         * Used for [org.mozilla.tv.firefox.ui.YouTubeNavigationTest].
+         * This will cause the test to wait until a specific condition is true before moving on.
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt]: EDIT: it looks like this is all deleted in a later commit.  Try to clean up previous commits when that happens (or at worst, go back and add a `TODO: deleted in a later commit`), otherwise this wastes a fair amount of review time.  (this is a mistake I've made frequently too, it's easy to forget)

~This kdoc would probably be better placed on the declaration on line 17.  Also, slight nit on the formatting:~

```kotlin
/**
 * This will cause the test to wait until a specific condition is true before moving on.
 *
 * @sample [org.mozilla.tv.firefox.ui.YouTubeNavigationTest]
 */
```
~(it's pretty generic functionality, it seems likely that we'll use it elsewhere too)~

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt [hunk 3]
```diff
@@ -25,9 +26,10 @@ class SessionLoadedIdlingResource : IdlingResource {
 
         val session = sessionManager.selectedSession
 
-        return if (session?.loading == true) {
+        return if (session?.loading == true && !ignoreLoading) {
             false
         } else {
+            ignoreLoading = false
             invokeCallback()
             true
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt]: Does this work consistently?  It seems like this is going to cause a race condition.  If `isIdleNow` is checked twice before a command is executed, it will block on `session.loading`.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/YouTubeNavigationTest.kt [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+            )
+        ))
+
+        customPocketFeedStateProvider.fakedPocketRepoState.onNext(mockedState)
+    }
+
+    @Test
+    fun youtubeNavigationTest() {
+        val youtubeUrl = "youtube.com/tv"
+        val youtubeFinalUrl = "youtube.com/tv#/surface?c=FEtopics&resume"
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/YouTubeNavigationTest.kt]: Nit: might be more clear to rename these `youTubeUrlBeforeRedirects` and `youTubeUrlAfterRedirects`

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 5]
```diff
@@ -67,6 +67,10 @@ class NavigationOverlayRobot {
                 .check(matches(withHint(R.string.urlbar_hint)))
     }
 
+    fun waitForURLBarToDisplayHint() {
+        device.wait(Until.findObject(By.textContains("")), 5000)
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: This seems misleading.  The current functionality looks more like `waitUntilAnyElementContainsEmptyText`.  Is there any way we can target this on the URL bar?

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt [hunk 6]
```diff
@@ -80,6 +84,10 @@ class NavigationOverlayRobot {
 
     fun assertActivityFinishing(activity: MainActivityTestRule) = assertTrue(activity.activity.isFinishing)
 
+    fun waitForYouTubeRedirects(url: String) {
+        device.wait(Until.findObject(By.textContains(url)), 5000)
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: See above comment on targetting this at the URL bar.

Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt]: This function is very generic, but the name is extremely specific.  I think this should be broken into two methods, `waitUntilYouTubeHomeLoads` and `waitUntil YouTubeVideoLoads`.  Better that the robot contains that kind of implementation detail.

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt (hunk 2 above)
Comment (dnarcese) [reply app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt]: Ah, sorry. I left the commit just in case I needed to go back to it again. But there are better ways I can handle that.

Comment (Baron-Severin) [reply app/src/androidTest/java/org/mozilla/tv/firefox/helpers/SessionLoadedIdlingResource.kt]: All good, as I said, I've done the same many times.

File: app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt [hunk 7]
```diff
@@ -35,7 +34,6 @@ class MainActivityTestRule(
      * implementation changes and the tests break. In that case, this code might be
      * broken because it's not used, and thus tested, at present.
      */
-    @VisibleForTesting
     lateinit var loadingIdlingResource: SessionLoadedIdlingResource
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/helpers/MainActivityTestRule.kt]: Nit: I get why we need to relax the visibility on this, but I think we should put a private set on it.
