### PR TITLE
Closes #2860: Open overlay when onboarding is shown

### LINKED ISSUE #2860: Dismissing Onboarding screen should take user to home screen overlay
## Steps to reproduce

1. Log in to your account on FFTV
2. Receive tab onboarding screen should be shown. Hit Dismiss

### Expected behavior

You are returned to the homescreen

### Actual behavior

You are returned to the sign in confirmation page

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### PR DESCRIPTION
**Pull request by psymoon**
## Checklist

- [x] Confirm the **acceptance criteria** is fully satisfied in the issue(s) this PR will close
- [x] Add thorough **tests** or an explanation of why it does not
- [x] Add a **CHANGELOG entry** if applicable
- [x] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-notneeded`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/NavigationOverlayFragment.kt [hunk 1]
```diff
@@ -280,6 +280,7 @@ class NavigationOverlayFragment : Fragment() {
 
                         val settings = Settings.getInstance(context!!)
                         if (settings.shouldShowFxaOnboarding()) {
+                            serviceLocator.screenController.showNavigationOverlay(fragmentManager, true)
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/NavigationOverlayFragment.kt]: With the current implementation, I think this is the right way to do this. However, I just want to mention that ideally this and `showFxaOnboardingScreen` would actually be called from the callback we get for login success – namely, the function that calls `finishAuthentication...` in `FxaRepo` – so we don't have to maintain "did we see onboarding?" state. Perhaps in a future refactor. :)
