### PR TITLE
[merge after release] Closes #2864: Fix toasts not showing up

### LINKED ISSUE #2864: Desktop requested / Non-desktop requested toast message is no longer visible
## Steps to reproduce
- Go to website
- Go back to overlay, and select 'request desktop...' button

### Expected behavior
- Desktop version opens, with the toast message indicating that desktop version is requested

### Actual behavior
- No toast message

### Device information
* Fire TV device: Cube, Gen 2
* Latest affected Firefox version: master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### PR DESCRIPTION
**Pull request by Baron-Severin**
## Checklist

- [x] Confirm the **acceptance criteria** is fully satisfied in the issue(s) this PR will close
- [x] Add thorough **tests** or an explanation of why it does not
- [x] Add a **CHANGELOG entry** if applicable
- [ ] Add **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-notneeded`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/NavigationOverlayFragment.kt [hunk 1]
```diff
@@ -167,12 +169,14 @@ class NavigationOverlayFragment : Fragment() {
...
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
-        ToolbarUiController(
+        toolbarUiController = ToolbarUiController(
             toolbarViewModel,
             ::exitFirefox,
             onNavigationEvent,
             serviceLocator.experimentsProvider
-        ).onCreateView(view, viewLifecycleOwner, fragmentManager!!)
+        ).apply {
+            onViewCreated(view)
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/NavigationOverlayFragment.kt]: nit: this whole block of code should actually be in `onCreateView` rather than renaming this method: `onViewCreated` is intended for sub-classes of custom Fragments so they can react to `onCreateView` without having to override, and potentially mess up, `onCreateView`: see the javadoc of these methods for details.

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt [hunk 2]
```diff
@@ -51,7 +51,7 @@ class ToolbarViewModel(
     val events = _events.hide()
 
     @Deprecated(message = "Use ToolbarViewModel.events for new code")
-    val legacyEvents: LiveData<Consumable<Action>> = LiveDataReactiveStreams
+    val legacyEvents: LiveData<Consumable<Action>> = LiveDataReactiveStreams // TODO update test, remove this
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt]: There appear to be no consumers: can we remove this?

If not, nit: can you elaborate in the comment on what "update test" means? Does that mean move it from `legacyEvents` to `events`?

File: app/src/test/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModelTest.kt [hunk 3]
```diff
@@ -158,20 +162,18 @@ class ToolbarViewModelTest {
 
     @Test
     fun `WHEN new session state url is not home THEN no overlay visibility event should be emitted`() {
```
Comment (mcomella) [inline app/src/test/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModelTest.kt]: I think this test needs to be updated to the non-deprecated version.

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarUiController.kt [hunk 4]
```diff
@@ -121,7 +127,11 @@ class ToolbarUiController(
         setOnFocusChangeListener { _, hasFocus -> if (!hasFocus) hasUserChangedURLSinceEditTextFocused = false }
     }
 
-    private fun initToolbar(layout: View, viewLifecycleOwner: LifecycleOwner, fragmentManager: FragmentManager) {
+    fun observeToolbarState(
+        layout: View,
+        viewLifecycleOwner: LifecycleOwner,
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarUiController.kt]: I think we're creating multiple observers to `toolbarViewModel.legacyState`: I think you should separate this back into `initToolbar` and `observeToolbarState`, unless you plan to convert it all to Rx.

File: CHANGELOG.md [hunk 5]
```diff
@@ -17,6 +17,9 @@ It diverges in the following ways:
 - (disabled by default) Dialog prompting users to manually upgrade the app
 - Firefox Account sign in and Send Tab is available to release users
 
+### Fixed
+- Toasts for pinning/unpinning and desktop mode (#2864)
```
Comment (mcomella) [inline CHANGELOG.md]: nit: what's fixed about the toasts? With this wording, it's unclear what was ever broken (i.e. they don't appear).

**Comment by Baron-Severin** [comment]
> Why was this broken in the first place? It's not clear to me from the code or why porting it to Rx fixes this issue.

@mcomella it broke when the original `LiveData` implementation was moved to Rx. We didn't notice, but if events were sent in rapid succession, some were dropped.  Best guess is that Google's conversion uses `postValue`, which we've seen similar behavior from in the past.  I don't think it's worth the time to investigate beyond that.

File: app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarUiController.kt [hunk 6]
```diff
@@ -135,9 +142,8 @@ class ToolbarUiController(
 
         layout.turboButton.setImageResource(turboButtonContent.imageId)
 
-        @Suppress("DEPRECATION")
-        toolbarViewModel.legacyState.observe(viewLifecycleOwner, Observer {
-            if (it == null) return@Observer
+        val stateDisposable = toolbarViewModel.state.subscribe {
+            if (it == null) return@subscribe
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarUiController.kt]: it can't be null anymore because it's Rx, right? I wonder if that's indicative of a possible crash here (because it actually can be null) or if this was just to fix the Nullable compiler warning.

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarUiController.kt]: It's just for the compiler.  Annoying, but better than a suppression.

**Comment by Baron-Severin** [comment]
> Why were multiple events being sent in rapid succession? It seems the only events sent here are show pinned toast, show desktop toast, exit firefox, and hide overlay. **Is it because hide overlay + show pinned toast gets called from the same method?**

Yeah, as far as I can tell that's why.
