### PR TITLE
Closes #1720: Pause all video playbacks when transtioning to settings

### LINKED ISSUE #1720: Clearing data while video playback crashes app
## Steps to reproduce
- Go to 680news.com (or youtube), open a video for fullscreen playback
- Click menu button, go to settings, and clear data

### Expected behavior
- Data cleared, app returns to Settings

### Actual behavior
- App crashes
### Device information

* Fire TV device: Fire TV basic
* Firefox version: 3.3.0 LAT

### PR DESCRIPTION
**Pull request by psymoon**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] The **UI tests** are passing after this PR (`./gradlew connectedDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt [hunk 1]
```diff
@@ -85,6 +86,11 @@ class ScreenController {
     }
 
     fun showSettingsScreen(fragmentManager: FragmentManager) {
+        /**
+         *  Pause all the videos when transitioning to [SettingsFragment] to mitigate possible memory
+         *  leak when clearing data. See [WebViewCache.clear] as well as #1720
+         */
+        fragmentManager.webRenderFragment().webView?.pauseAllVideoPlaybacks()
```
Comment (Baron-Severin) [inline app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: I'm uncomfortable that the `ScreenController` is calling directly into a `WebView`, but I'm trying to figure out a cleaner alternative and coming up dry.  @mcomella, @liuche do you have any thoughts here?

Comment (psymoon) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Yeah I agree, ideally it would've been in the lifecycle method of it's respective fragment.

Comment (liuche) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Hm, can we add the webView handling code into `onStop` and then call that? I know it's further mixing our lifecycle vs manual fragment handling.

Comment (psymoon) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: @liuche You mean to override `EngineView.onStop()`?

Comment (mcomella) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: I wonder if `ScreenController` should become something more like `ScreenRepo`: what if the WebRenderFragment reacted to the current active screen and paused all the videos when the active screen is changed? Since we don't care about sync/async timing so much, I think that'd be fine.

fwiw, in #1797 (still needs to land), I made `currentActiveScreen` into a LiveData you can listen to.

Comment (Baron-Severin) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: @mcomella I really like that solution.  @psymoon sorry for blocking this one so long, but what do you think about that suggestion?

Comment (psymoon) [reply app/src/main/java/org/mozilla/tv/firefox/ScreenController.kt]: Sounds good to me
