### PR TITLE
Issue #1861: Improve the UITest Error Output

### LINKED ISSUE #1861: Remote UI test failures log misleading failure messages
PRs are occasionally failing when TC appears to fail to download all necessary files for our remote UI testing.  @liuche and I have each seen this once today.  Restarting the PR was enough to get the build to pass.

Full TC logs at https://tools.taskcluster.net/groups/JGcX5ElRRw6WIG9Go2M5hA/tasks/JGcX5ElRRw6WIG9Go2M5hA/runs/0/logs/public%2Flogs%2Flive.log
Logs that look relevent included below
```
/ [0/6 files][    0.0 B/ 15.0 MiB]   0% Done                                    
CommandException: 
Downloading this composite object requires integrity checking with CRC32c,
but your crcmod installation isn't using the module's C extension, so the
hash computation will likely throttle download performance. For help
installing the extension, please see "gsutil help crcmod".
To download regardless of crcmod performance or to skip slow integrity
checks, see the "check_hashes" option in your boto config file.
NOTE: It is strongly recommended that you not disable integrity checks. Doing so
could allow data corruption to go undetected during uploading/downloading.
/ [1/6 files][ 30.0 KiB/ 15.0 MiB]   0% Done                                    
/ [2/6 files][ 37.5 KiB/ 15.0 MiB]   0% Done                                    
/ [3/6 files][  2.7 MiB/ 15.0 MiB]  18% Done                                    
/ [4/6 files][  5.3 MiB/ 15.0 MiB]  35% Done                                    
-
- [5/6 files][ 13.3 MiB/ 15.0 MiB]  89% Done                                    
CommandException: 1 file/object could not be transferred.
+ exit 10
[taskcluster 2019-02-19 23:32:00.143Z] === Task Finished ===
[taskcluster 2019-02-19 23:33:21.929Z] Unsuccessful task run with exit code: 10 completed in 1361.287 seconds

```

### PR DESCRIPTION
**Pull request by npark-mozilla**
Fixes #1861 

### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [ ] This PR includes a **CHANGELOG entry** or does not need one
- [ ] The **UI tests** are passing after this PR (`./gradlew connectedSystemDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: tools/taskcluster/execute-firebase-test.sh [hunk 1]
```diff
@@ -55,7 +55,11 @@ exitcode=$?
 echo "Downloading artifacts"
 
 mkdir test_artifacts
-./google-cloud-sdk/bin/gsutil ls gs://firefox-tv_test_artifacts | tail -1 | ./google-cloud-sdk/bin/gsutil -m cp -r -I ./test_artifacts
+./google-cloud-sdk/bin/gsutil ls gs://firefox-tv_test_artifacts | tail -1 | ./google-cloud-sdk/bin/gsutil cp -r -I ./test_artifacts > /dev/null 2>&1
 
 # Now exit the script with the exit code from the test run. (Only 0 if all test executions passed)
+if [[ $exitcode -ne 0 ]]; then
+    echo "UI Test(s) have failed, please check the test artifacts folder"
```
Comment (Baron-Severin) [inline tools/taskcluster/execute-firebase-test.sh]: This is definitely a step up, but I think we can make this more clear.  The test artifacts folder contains a LOT of files, and it takes a while of sifting through to figure out where the actual error is.

When we run tests locally we see a list of executed tests, which those that failed marked in red up at the top.  I think that should be our goal here, too.

I know that JUnit generates HTML docs when it runs these tests.  I saw a bunch of them for our unit tests in the Test Artifacts folder, and I've seen them after running Espresso locally too.  Is there any way we can pull that file into test artifacts along with everything else, then point to it in this log statement?

Comment (npark-mozilla) [reply tools/taskcluster/execute-firebase-test.sh]: Most of the test artifacts folder contents are from compile/unit test execution, and anything to do with firebase execution is saved separately into the `test_artifacts` folder for easy discretion.

When Firebase executes UI test, it does not produce HTML docs (and many other docs) unlike local execution, because they want you to log into Firebase to see the results in its own UI. This also happens if you submit tests to Firebase from your local computer.  You won't be able to see which tests have failed, because they want us to log into Firebase for that.

It does save an XML doc within `test_artifacts` folder, containing some details of the test result.  So, if we really want to do that, we need to go into the downloaded folder, fetch the xml file, then parse it to filter the entries of failed tests, and print it out on the log.  But that would be a lot of work (which we probably won't have time to do) compared to just going into the specified URL in the log.

Comment (Baron-Severin) [reply tools/taskcluster/execute-firebase-test.sh]: Would it be possible to log "Test failed. View test results at www.some.firebase.url/mytestrunid"?

Comment (npark-mozilla) [reply tools/taskcluster/execute-firebase-test.sh]: hmm, I somehow need to save the output of the gcloud command as json, and seek for the line that contains the URL.  this could be easier.  I'll give a day to see whether I can figure it out.  If not, we can raise a separate bug for this so someone with better scripting knowledge can take out.

Comment (npark-mozilla) [reply tools/taskcluster/execute-firebase-test.sh]: Actually, there was an easier way.  Disable downloading of artifacts.

**Comment by npark-mozilla** [comment]
screen shot 2019-02-23 at 6 07 07 pm
