### PR TITLE
Closes #936: Move WebView.onPause to onStop

### LINKED ISSUE #936: [Voice] "Alexa, pause" on youtube.com/tv doesn't work consistently, shows black screen
### Steps to reproduce
On cube:
- Open youtube.com/tv, select video
- Say, "Alexa pause"

### Expected behavior
Alexa pauses

### Actual behavior
Alexa pauses while you speak but starts the video again. The video seems to do a reload thing and sometimes will pause.

If we comment out the `onPause/pauseTimers` WebView methods (and resume counterparts), the video will pause when speaking, start playing again, and pause a few moments later (I assume Alexa sends media button events). I think we can fix the pause afterwards by implementing [this optimization suggested by the MediaSession docs](https://developer.amazon.com/docs/fire-tv/mediasession-api-integration.html#enhanced-experience-for-voice-enabled-playback-controls-using-media-session-optional).

We should investigate what the expected behavior for Alexa is: should we be calling onPause in onPause? What about pauseTimers? Will it all just work if we implement the optimization above?

Note how this functionality will intersect with #930, which implements the MediaSession APIs to support this functionality.

---

Note that fixing this *does not* implement other MediaSession functionality:
- Rewind/fast-forward
- Next/previous
- Restart

### PR DESCRIPTION
**Pull request by mcomella**
Unfortunately, there are a lot of unknowns here about side effects.

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt [hunk 1]
```diff
@@ -66,17 +66,17 @@ abstract class IWebViewLifecycleFragment : LocaleAwareFragment() {
 
     override fun onPause() {
         webView!!.saveWebViewState(session)
-        webView!!.onPause()
-        webView!!.pauseTimers()
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt]: Can we verify if the video pausing is because of `pauseTimers` vs `onPause`? Looking at the documentation for `pauseTimers` it seems like that should actually be called in `onStop` rather than `onPause`.

If it's in fact `onPause` I'm fine with this change, but I do wonder...

`Pauses all layout, parsing, and JavaScript timers for all WebViews. This is a global requests, not restricted to just this WebView. This can be useful if the application has been paused.`

^ This sounds like it might be the culprit, not `onPause`.

Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt]: > Can we verify if the video pausing is because of pauseTimers vs onPause

I definitely needed to comment out `onPause` to get this behavior to stop happening but I don't remember if `pauseTimers` needed to be moved too or not: maybe we should test this before landing.

> Looking at the documentation for pauseTimers it seems like that should actually be called in onStop rather than onPause

The docs make me think `pauseTimers` could be called from `onPaused`: "This can be useful if the application has been paused." But it doesn't specify: might be fine to call from `onStop` too.

Comment (liuche) [reply app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt]: Specifically commenting out `webView!!.onPause()`, right?

Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt]: Yes. I want to reverify the behaviors, however, before landing.

Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/iwebview/IWebViewLifecycleFragment.kt]: I verified the video pauses because of `WebView.onPause`. In fact, I can still call `pauseTimers` in `onPause` if I move `WebView.onPause` to `onStop`: I pushed an amended commit with this change.
