### PR TITLE
Closes #1448: Fix up NetworkPageLoadTest

### LINKED ISSUE #1448: [1364] PageLoadTest fails; convert to Robot pattern & make NetworkPageLoadTest
BasicNavigationTest does basic browser navigation with local files so now we really only want this test to make sure the network part of page loads is still working. Fix it, move it to our Robot pattern, and make it clear it's only for network page loads.

I think the failure is caused because the page layout changed: we should use pages we have control over. Here's the failure:
```
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "mozilla"' doesn't match the selected view.
Expected: with text: a string containing "mozilla"
Got: "InlineAutocompleteEditText{id=2131296531, res-name=navUrlInput, visibility=VISIBLE, width=996, height=96, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@288a658, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x11 imeOptions=0x1a000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=Search or enter address label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=114.0, y=204.0, text=https://www.google-analytics.com/analytics.js, hint=Search or enter address, input-type=17, ime-target=true, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:314)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:297)
at org.mozilla.tv.firefox.ui.PageLoadTest.PageLoadTest(PageLoadTest.java:83)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: junit.framework.AssertionFailedError: 'with text: a string containing "mozilla"' doesn't match the selected view.
Expected: with text: a string containing "mozilla"
Got: "InlineAutocompleteEditText{id=2131296531, res-name=navUrlInput, visibility=VISIBLE, width=996, height=96, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@288a658, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x11 imeOptions=0x1a000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=Search or enter address label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=114.0, y=204.0, text=https://www.google-analytics.com/analytics.js, hint=Search or enter address, input-type=17, ime-target=true, has-links=false}"

at android.support.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:539)
at android.support.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:103)
at android.support.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:415)
at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:279)
at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:265)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### PR DESCRIPTION
**Pull request by mcomella**
Ignore 1441 please.

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt [hunk 1]
```diff
@@ -18,8 +18,7 @@ import org.mozilla.tv.firefox.helpers.MainActivityTestRule
 // the linting error for starting a function with an uppercase letter
 class LiveDataMapTest {
 
-    @Rule @JvmField
-    val activityTestRule = MainActivityTestRule()
+    @Rule @JvmField val activityTestRule = MainActivityTestRule()
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt]: I like the convention of inlining annotations, but it should be mentioned that it violates JetBrains and Android style guides.  We should probably decide on one strategy with regards to this and apply it everywhere.

https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting
https://developer.android.com/kotlin/style-guide#annotations

It is however supported by the Square Android style guide (I can't find a link in natural language, it's in here somewhere https://github.com/square/java-code-styles/blob/master/configs/codestyles/SquareAndroid.xml).

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/screenshots/PocketOnboardTest.java [hunk 2]
```diff
@@ -42,8 +43,7 @@
     public static final LocaleTestRule localeTestRule = new LocaleTestRule();
 
     @Rule
-    public ActivityTestRule<MainActivity> mActivityTestRule = new ActivityTestRule<MainActivity>(MainActivity.class,
-            false, false);
+    public ActivityTestRule<MainActivity> mActivityTestRule = new MainActivityTestRule(false, false, false);
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/screenshots/PocketOnboardTest.java]: Might be worth removing the Hungarian notation (to be more consistent with the codebase) while touching this file.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt [hunk 3]
```diff
@@ -1,89 +1,43 @@
...
+
+        navigationOverlay { }.enterUrlAndEnterToBrowser(googleUrl) {
+            assertDOMElementExists(Locator.ID, "hplogo") // google logo
+        }.openOverlay {
+            assertURLBarTextContains("google")
+
+        }.enterUrlAndEnterToBrowser(mozillaUrl) {
+            assertDOMElementExists(Locator.CLASS_NAME, "mzp-c-navigation-logo") // mozilla logo
+        }.openOverlay {
+//            assertURLBarTextContains("mozilla") // TODO: on emulators, url is not always the website just visited. (#1444)
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt]: It would be possible to work around this by disabling turbo mode.  This problem is only present on emulators, so that may be acceptable. 🤷‍♂️

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt [hunk 4]
```diff
@@ -1,89 +1,43 @@
...
+import org.mozilla.tv.firefox.ui.robots.navigationOverlay
+
+/**
+ * Tests that the browser can successfully load pages from the network. This works with our other UI tests
+ * which should load content from the disk to make them less fragile.
+ *
+ * This test loads a few pages off the network and verifies their content to ensure they're actually loaded.
+ * Verification is minimal to reduce the chance of the test breaking from the web page changing.
+ */
 class PageLoadTest {
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt]: Suggest adding `android.support.test.filters.FlakyTest` annotation, with `detail` arg.

File: app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt (hunk 1 above)
Comment (mcomella) [reply app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt]: 🦅 eyes over here! I remember seeing `@Whatever fun...` is okay so I assumed two annotations would also be okay. Guess not! I'm fine placing the annotations together, above the fun. That being said, `@get:Rule` invalidates this.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/screenshots/PocketOnboardTest.java (hunk 2 above)
Comment (mcomella) [reply app/src/androidTest/java/org/mozilla/tv/firefox/ui/screenshots/PocketOnboardTest.java]: A good observation but I don't think it's worth the time: I was going to wait to touch up these files until we convert them to kotlin (and use the robot pattern).

File: app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt (hunk 1 above)
Comment (Baron-Severin) [reply app/src/androidTest/java/org/mozilla/tv/firefox/integration/LiveDataMapTest.kt]: Hah, we used the Square rules at my last job.  

Both guides claim that inlining a single annotation with no arguments is fine.  I'm not sure if `@get:Rule` counts as one or two, but it could potentially be allowed.

**Comment by mcomella** [comment]
I'm counting it at as one. :)

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt (hunk 3 above)
Comment (mcomella) [reply app/src/androidTest/java/org/mozilla/tv/firefox/ui/PageLoadTest.kt]: @Baron-Severin Good idea: I ended up disabling turbo mode (adding a comment about the workaround) and uncommenting this assertion. This required a minor refactor of Matchers.kt, which you may be interested in looking at but I'm not concerned so I didn't request another review.

File: app/src/androidTest/java/org/mozilla/tv/firefox/ui/NetworkPageLoadTest.kt [hunk 5]
```diff
@@ -31,15 +31,22 @@ class NetworkPageLoadTest {
         val googleUrl = "https://google.com".toUri()!!
         val mozillaUrl = "https://mozilla.org".toUri()!!
 
-        navigationOverlay { }.enterUrlAndEnterToBrowser(googleUrl) {
+        navigationOverlay {
+            // Work around for #1444: on emulators with turbo mode enabled, the url bar will display
+            // any url loaded by the page in addition to the primary url. We disable turbo mode to
+            // ensure we only see the primary url and can assert it correctly.
+            toggleTurbo() // enabled by default.
```
Comment (Baron-Severin) [inline app/src/androidTest/java/org/mozilla/tv/firefox/ui/NetworkPageLoadTest.kt]: Optional nit: it might be good to break this into `turnTurboOn` and `turnTurboOff`, each with an assertion, similarly to `BrowserRobot#openOverlay`.

Comment (mcomella) [reply app/src/androidTest/java/org/mozilla/tv/firefox/ui/NetworkPageLoadTest.kt]: Filed https://github.com/mozilla-mobile/firefox-tv/issues/1464
